global:
  scrape_interval: 15s
scrape_configs:
  - job_name: node
    static_configs:
      - targets: ["localhost:9100"]    # node-exporter on host network
  - job_name: cadvisor
    static_configs:
      - targets: ["cadvisor:8080"]